-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_tareas
(
    id serial NOT NULL,
    titulo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    recurrencia character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_vencimiento timestamp without time zone NOT NULL,
    proximo_aviso timestamp without time zone NOT NULL,
    notificado_email boolean DEFAULT false,
    activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_tareas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.afp_tasas_mensuales
(
    id serial NOT NULL,
    afp_id integer,
    anio integer NOT NULL,
    mes integer NOT NULL,
    aporte_obligatorio numeric(5, 4) DEFAULT 0.1000,
    comision_flujo numeric(5, 4) NOT NULL,
    comision_mixta_flujo numeric(5, 4) NOT NULL,
    prima_seguro numeric(5, 4) NOT NULL,
    comision_anual_saldo numeric(5, 4) DEFAULT 0,
    CONSTRAINT afp_tasas_mensuales_pkey PRIMARY KEY (id),
    CONSTRAINT afp_tasas_mensuales_afp_id_anio_mes_key UNIQUE (afp_id, anio, mes)
);

CREATE TABLE IF NOT EXISTS public.afps
(
    id serial NOT NULL,
    codigo_sbs character varying(10) COLLATE pg_catalog."default",
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    CONSTRAINT afps_pkey PRIMARY KEY (id),
    CONSTRAINT afps_codigo_sbs_key UNIQUE (codigo_sbs)
);

CREATE TABLE IF NOT EXISTS public.clasificadores_mef
(
    id serial NOT NULL,
    anio integer NOT NULL DEFAULT 2026,
    codigo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    codigo_limpio character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nivel integer NOT NULL,
    tipo_transaccion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    parent_id integer,
    CONSTRAINT clasificadores_mef_pkey PRIMARY KEY (id),
    CONSTRAINT clasificadores_mef_codigo_key UNIQUE (codigo),
    CONSTRAINT unique_anio_codigo UNIQUE (anio, codigo_limpio)
);

CREATE TABLE IF NOT EXISTS public.conceptos_afectaciones
(
    id serial NOT NULL,
    concepto_base_id integer NOT NULL,
    concepto_derivado_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT conceptos_afectaciones_pkey PRIMARY KEY (id),
    CONSTRAINT unique_afectacion UNIQUE (concepto_base_id, concepto_derivado_id)
);

CREATE TABLE IF NOT EXISTS public.conceptos_maestros
(
    id serial NOT NULL,
    codigo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    parent_id integer,
    CONSTRAINT conceptos_maestros_pkey PRIMARY KEY (id),
    CONSTRAINT conceptos_maestros_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.conceptos_modelo
(
    id serial NOT NULL,
    concepto_id integer NOT NULL,
    nombre_personalizado character varying(150) COLLATE pg_catalog."default" NOT NULL,
    frecuencia_meses character varying(50) COLLATE pg_catalog."default" DEFAULT '1,2,3,4,5,6,7,8,9,10,11,12'::character varying,
    clasificador_id integer,
    es_extraordinario boolean DEFAULT false,
    requiere_monto boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    es_pensionable boolean DEFAULT false,
    es_remunerativa boolean DEFAULT false,
    es_base_cts boolean DEFAULT false,
    es_base_beneficios_sociales boolean DEFAULT false,
    CONSTRAINT conceptos_modelo_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nombre_modelo UNIQUE (nombre_personalizado)
);

CREATE TABLE IF NOT EXISTS public.conceptos_tenant
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    concepto_id integer NOT NULL,
    nombre_personalizado character varying(150) COLLATE pg_catalog."default" NOT NULL,
    frecuencia_meses character varying(50) COLLATE pg_catalog."default" DEFAULT '1,2,3,4,5,6,7,8,9,10,11,12'::character varying,
    activo boolean DEFAULT true,
    clasificador_id integer,
    es_extraordinario boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    requiere_monto boolean DEFAULT false,
    modelo_id integer,
    es_pensionable boolean DEFAULT false,
    es_remunerativa boolean DEFAULT false,
    es_base_cts boolean DEFAULT false,
    es_base_beneficios_sociales boolean DEFAULT false,
    CONSTRAINT conceptos_tenant_pkey PRIMARY KEY (id),
    CONSTRAINT unique_tenant_modelo_id UNIQUE (tenant_id, modelo_id)
);

CREATE TABLE IF NOT EXISTS public.contratos
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    trabajador_id integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    puesto_id integer NOT NULL,
    tipo_contrato character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT contratos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fuentes_rubros
(
    id serial NOT NULL,
    anio integer NOT NULL,
    fuente_financiamiento character varying(150) COLLATE pg_catalog."default" NOT NULL,
    rubro character varying(150) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    codigo_fuente_rubro character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT fuentes_rubros_pkey PRIMARY KEY (id),
    CONSTRAINT unique_fuente_rubro_anio UNIQUE (anio, fuente_financiamiento, rubro)
);

CREATE TABLE IF NOT EXISTS public.goose_db_version
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT goose_db_version_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.metas_presupuestales
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    anio integer NOT NULL,
    codigo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(512) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT metas_presupuestales_pkey PRIMARY KEY (id),
    CONSTRAINT unique_meta_anio_tenant UNIQUE (tenant_id, anio, codigo)
);

CREATE TABLE IF NOT EXISTS public.notificaciones
(
    id serial NOT NULL,
    tenant_id integer,
    usuario_id integer,
    titulo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    mensaje text COLLATE pg_catalog."default" NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    leido boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notificaciones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ocurrencias_asistencia
(
    id serial NOT NULL,
    contrato_id integer NOT NULL,
    tipo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_ocurrencia date NOT NULL,
    cantidad numeric(10, 2) NOT NULL,
    procesado boolean DEFAULT false,
    planilla_id_descuento integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ocurrencias_asistencia_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.organigramas
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    documento_aprobacion character varying(200) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    fecha_vigencia date NOT NULL,
    activo boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT organigramas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pap_detalles
(
    id serial NOT NULL,
    version_id integer,
    meta_codigo character varying(50) COLLATE pg_catalog."default",
    meta_descripcion character varying(255) COLLATE pg_catalog."default",
    fuente_rubro_codigo character varying(50) COLLATE pg_catalog."default",
    fuente_rubro_descripcion character varying(255) COLLATE pg_catalog."default",
    clasificador_codigo_limpio character varying(50) COLLATE pg_catalog."default",
    clasificador_descripcion character varying(255) COLLATE pg_catalog."default",
    mes_01 numeric(10, 2) DEFAULT 0,
    mes_02 numeric(10, 2) DEFAULT 0,
    mes_03 numeric(10, 2) DEFAULT 0,
    mes_04 numeric(10, 2) DEFAULT 0,
    mes_05 numeric(10, 2) DEFAULT 0,
    mes_06 numeric(10, 2) DEFAULT 0,
    mes_07 numeric(10, 2) DEFAULT 0,
    mes_08 numeric(10, 2) DEFAULT 0,
    mes_09 numeric(10, 2) DEFAULT 0,
    mes_10 numeric(10, 2) DEFAULT 0,
    mes_11 numeric(10, 2) DEFAULT 0,
    mes_12 numeric(10, 2) DEFAULT 0,
    total_anual numeric(12, 2) DEFAULT 0,
    CONSTRAINT pap_detalles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pap_versiones
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    anio integer NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_generacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'CERRADA'::character varying,
    CONSTRAINT pap_versiones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.parametros_globales
(
    id serial NOT NULL,
    clave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    valor numeric(15, 4) NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_desde date NOT NULL,
    fecha_hasta date,
    CONSTRAINT parametros_globales_pkey PRIMARY KEY (id),
    CONSTRAINT unique_clave_fecha UNIQUE (clave, fecha_desde)
);

CREATE TABLE IF NOT EXISTS public.planilla_conceptos
(
    id serial NOT NULL,
    planilla_detalle_id integer NOT NULL,
    concepto_tenant_id integer,
    tipo_concepto character varying(20) COLLATE pg_catalog."default" NOT NULL,
    monto numeric(10, 2) NOT NULL,
    maestro_id integer NOT NULL DEFAULT 0,
    codigo_sunat character varying(10) COLLATE pg_catalog."default",
    nombre_en_boleta character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT planilla_conceptos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.planilla_detalles
(
    id serial NOT NULL,
    planilla_id integer NOT NULL,
    contrato_id integer NOT NULL,
    total_ingresos numeric(10, 2) DEFAULT 0.00,
    total_retenciones numeric(10, 2) DEFAULT 0.00,
    total_aportes numeric(10, 2) DEFAULT 0.00,
    neto_pagar numeric(10, 2) DEFAULT 0.00,
    trabajador_nombre_completo character varying(250) COLLATE pg_catalog."default",
    trabajador_numero_documento character varying(20) COLLATE pg_catalog."default",
    puesto_codigo_airhsp character varying(50) COLLATE pg_catalog."default",
    puesto_nombre character varying(200) COLLATE pg_catalog."default",
    organigrama_documento_aprobacion character varying(200) COLLATE pg_catalog."default",
    unidad_organica_nombre character varying(200) COLLATE pg_catalog."default",
    unidad_organica_tipo character varying(50) COLLATE pg_catalog."default",
    sueldo_basico_historico numeric(10, 2),
    CONSTRAINT planilla_detalles_pkey PRIMARY KEY (id),
    CONSTRAINT unique_detalle_contrato UNIQUE (planilla_id, contrato_id)
);

CREATE TABLE IF NOT EXISTS public.planillas
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    anio integer NOT NULL,
    mes integer NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'BORRADOR'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT planillas_pkey PRIMARY KEY (id),
    CONSTRAINT unique_planilla_mes UNIQUE (tenant_id, anio, mes, descripcion)
);

CREATE TABLE IF NOT EXISTS public.puesto_conceptos
(
    id serial NOT NULL,
    puesto_id integer NOT NULL,
    concepto_tenant_id integer NOT NULL,
    monto numeric(10, 2),
    activo boolean DEFAULT true,
    CONSTRAINT puesto_conceptos_pkey PRIMARY KEY (id),
    CONSTRAINT unique_puesto_concepto UNIQUE (puesto_id, concepto_tenant_id)
);

CREATE TABLE IF NOT EXISTS public.puestos
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    meta_id integer,
    fuente_rubro_id integer,
    regimen_id integer NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    sueldo_presupuestado numeric(10, 2) NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'VACANTE'::character varying,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    es_dietario boolean DEFAULT false,
    unidad_organica_id integer,
    codigo_airhsp character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT puestos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.regimen_concepto_modelo
(
    regimen_id integer NOT NULL,
    concepto_modelo_id integer NOT NULL,
    CONSTRAINT regimen_concepto_modelo_pkey PRIMARY KEY (regimen_id, concepto_modelo_id)
);

CREATE TABLE IF NOT EXISTS public.regimen_concepto_tenant
(
    tenant_id integer NOT NULL,
    regimen_id integer NOT NULL,
    concepto_tenant_id integer NOT NULL,
    CONSTRAINT regimen_concepto_tenant_pkey PRIMARY KEY (tenant_id, regimen_id, concepto_tenant_id)
);

CREATE TABLE IF NOT EXISTS public.regimenes_laborales
(
    id serial NOT NULL,
    codigo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT regimenes_laborales_pkey PRIMARY KEY (id),
    CONSTRAINT regimenes_laborales_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.tenants
(
    id serial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ruc character varying(11) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    direccion character varying(255) COLLATE pg_catalog."default",
    frase_gestion character varying(255) COLLATE pg_catalog."default",
    logo_url character varying(255) COLLATE pg_catalog."default",
    slug character varying(100) COLLATE pg_catalog."default",
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tenants_pkey PRIMARY KEY (id),
    CONSTRAINT tenants_ruc_key UNIQUE (ruc),
    CONSTRAINT tenants_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.trabajadores
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    tipo_documento character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DNI'::character varying,
    numero_documento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido_paterno character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido_materno character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date,
    sexo character varying(1) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    regimen_pensionario character varying(20) COLLATE pg_catalog."default" DEFAULT 'ONP'::character varying,
    afp_id integer,
    afp_tipo_comision character varying(10) COLLATE pg_catalog."default",
    cuspp character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT trabajadores_pkey PRIMARY KEY (id),
    CONSTRAINT unique_documento_tenant UNIQUE (tenant_id, tipo_documento, numero_documento)
);

CREATE TABLE IF NOT EXISTS public.unidades_organicas
(
    id serial NOT NULL,
    tenant_id integer NOT NULL,
    organigrama_id integer NOT NULL,
    parent_id integer,
    codigo_mef character varying(50) COLLATE pg_catalog."default",
    nombre character varying(200) COLLATE pg_catalog."default" NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unidades_organicas_pkey PRIMARY KEY (id),
    CONSTRAINT unique_organigrama_nombre UNIQUE (organigrama_id, nombre)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    tenant_id integer,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.afp_tasas_mensuales
    ADD CONSTRAINT afp_tasas_mensuales_afp_id_fkey FOREIGN KEY (afp_id)
    REFERENCES public.afps (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clasificadores_mef
    ADD CONSTRAINT clasificadores_mef_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES public.clasificadores_mef (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.conceptos_afectaciones
    ADD CONSTRAINT conceptos_afectaciones_concepto_base_id_fkey FOREIGN KEY (concepto_base_id)
    REFERENCES public.conceptos_maestros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.conceptos_afectaciones
    ADD CONSTRAINT conceptos_afectaciones_concepto_derivado_id_fkey FOREIGN KEY (concepto_derivado_id)
    REFERENCES public.conceptos_maestros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.conceptos_maestros
    ADD CONSTRAINT conceptos_maestros_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES public.conceptos_maestros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.conceptos_modelo
    ADD CONSTRAINT conceptos_modelo_clasificador_id_fkey FOREIGN KEY (clasificador_id)
    REFERENCES public.clasificadores_mef (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.conceptos_modelo
    ADD CONSTRAINT conceptos_modelo_concepto_id_fkey FOREIGN KEY (concepto_id)
    REFERENCES public.conceptos_maestros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.conceptos_tenant
    ADD CONSTRAINT conceptos_tenant_clasificador_id_fkey FOREIGN KEY (clasificador_id)
    REFERENCES public.clasificadores_mef (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.conceptos_tenant
    ADD CONSTRAINT conceptos_tenant_concepto_id_fkey FOREIGN KEY (concepto_id)
    REFERENCES public.conceptos_maestros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.conceptos_tenant
    ADD CONSTRAINT conceptos_tenant_modelo_id_fkey FOREIGN KEY (modelo_id)
    REFERENCES public.conceptos_modelo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.conceptos_tenant
    ADD CONSTRAINT conceptos_tenant_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_conceptos_tenant_tid
    ON public.conceptos_tenant(tenant_id);


ALTER TABLE IF EXISTS public.contratos
    ADD CONSTRAINT contratos_puesto_id_fkey FOREIGN KEY (puesto_id)
    REFERENCES public.puestos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_contratos_puesto
    ON public.contratos(puesto_id);


ALTER TABLE IF EXISTS public.contratos
    ADD CONSTRAINT contratos_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_contratos_tenant
    ON public.contratos(tenant_id);


ALTER TABLE IF EXISTS public.contratos
    ADD CONSTRAINT contratos_trabajador_id_fkey FOREIGN KEY (trabajador_id)
    REFERENCES public.trabajadores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_contratos_trabajador
    ON public.contratos(trabajador_id);


ALTER TABLE IF EXISTS public.metas_presupuestales
    ADD CONSTRAINT metas_presupuestales_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notificaciones
    ADD CONSTRAINT notificaciones_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notificaciones
    ADD CONSTRAINT notificaciones_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ocurrencias_asistencia
    ADD CONSTRAINT ocurrencias_asistencia_contrato_id_fkey FOREIGN KEY (contrato_id)
    REFERENCES public.contratos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.organigramas
    ADD CONSTRAINT organigramas_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_organigramas_tenant
    ON public.organigramas(tenant_id);


ALTER TABLE IF EXISTS public.pap_detalles
    ADD CONSTRAINT pap_detalles_version_id_fkey FOREIGN KEY (version_id)
    REFERENCES public.pap_versiones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.planilla_conceptos
    ADD CONSTRAINT planilla_conceptos_concepto_tenant_id_fkey FOREIGN KEY (concepto_tenant_id)
    REFERENCES public.conceptos_tenant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.planilla_conceptos
    ADD CONSTRAINT planilla_conceptos_planilla_detalle_id_fkey FOREIGN KEY (planilla_detalle_id)
    REFERENCES public.planilla_detalles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.planilla_detalles
    ADD CONSTRAINT planilla_detalles_contrato_id_fkey FOREIGN KEY (contrato_id)
    REFERENCES public.contratos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.planilla_detalles
    ADD CONSTRAINT planilla_detalles_planilla_id_fkey FOREIGN KEY (planilla_id)
    REFERENCES public.planillas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.planillas
    ADD CONSTRAINT planillas_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.puesto_conceptos
    ADD CONSTRAINT puesto_conceptos_concepto_tenant_id_fkey FOREIGN KEY (concepto_tenant_id)
    REFERENCES public.conceptos_tenant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.puesto_conceptos
    ADD CONSTRAINT puesto_conceptos_puesto_id_fkey FOREIGN KEY (puesto_id)
    REFERENCES public.puestos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_puesto_conceptos_pid
    ON public.puesto_conceptos(puesto_id);


ALTER TABLE IF EXISTS public.puestos
    ADD CONSTRAINT puestos_fuente_rubro_id_fkey FOREIGN KEY (fuente_rubro_id)
    REFERENCES public.fuentes_rubros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.puestos
    ADD CONSTRAINT puestos_meta_id_fkey FOREIGN KEY (meta_id)
    REFERENCES public.metas_presupuestales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.puestos
    ADD CONSTRAINT puestos_regimen_id_fkey FOREIGN KEY (regimen_id)
    REFERENCES public.regimenes_laborales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.puestos
    ADD CONSTRAINT puestos_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_puestos_tenant
    ON public.puestos(tenant_id);


ALTER TABLE IF EXISTS public.puestos
    ADD CONSTRAINT puestos_unidad_organica_id_fkey FOREIGN KEY (unidad_organica_id)
    REFERENCES public.unidades_organicas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.regimen_concepto_modelo
    ADD CONSTRAINT regimen_concepto_modelo_concepto_modelo_id_fkey FOREIGN KEY (concepto_modelo_id)
    REFERENCES public.conceptos_modelo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.regimen_concepto_modelo
    ADD CONSTRAINT regimen_concepto_modelo_regimen_id_fkey FOREIGN KEY (regimen_id)
    REFERENCES public.regimenes_laborales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.regimen_concepto_tenant
    ADD CONSTRAINT regimen_concepto_tenant_concepto_tenant_id_fkey FOREIGN KEY (concepto_tenant_id)
    REFERENCES public.conceptos_tenant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.regimen_concepto_tenant
    ADD CONSTRAINT regimen_concepto_tenant_regimen_id_fkey FOREIGN KEY (regimen_id)
    REFERENCES public.regimenes_laborales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.regimen_concepto_tenant
    ADD CONSTRAINT regimen_concepto_tenant_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.trabajadores
    ADD CONSTRAINT trabajadores_afp_id_fkey FOREIGN KEY (afp_id)
    REFERENCES public.afps (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trabajadores
    ADD CONSTRAINT trabajadores_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_trabajadores_tenant
    ON public.trabajadores(tenant_id);


ALTER TABLE IF EXISTS public.unidades_organicas
    ADD CONSTRAINT unidades_organicas_organigrama_id_fkey FOREIGN KEY (organigrama_id)
    REFERENCES public.organigramas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_unidades_organicas_org
    ON public.unidades_organicas(organigrama_id);


ALTER TABLE IF EXISTS public.unidades_organicas
    ADD CONSTRAINT unidades_organicas_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES public.unidades_organicas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.unidades_organicas
    ADD CONSTRAINT unidades_organicas_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;