-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS sunat_tipos_suspension (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    descripcion TEXT NOT NULL,
    descripcion_abreviada VARCHAR(150) NOT NULL,
    tipo_suspension VARCHAR(20) NOT NULL, -- 'PERFECTA' o 'IMPERFECTA'
    activo BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sunat_tipos_suspension (codigo, descripcion, descripcion_abreviada, tipo_suspension, activo) VALUES
('01', 'S.P. SANCIÓN DISCIPLINARIA', 'S.P. SANCIÓN DISCIPLINARIA', 'PERFECTA', true),
('02', 'S.P. EJERCICIO DEL DERECHO DE HUELGA', 'S.P. EJERCICIO DERECHO HUELGA', 'PERFECTA', true),
('03', 'S.P. DETENCIÓN DEL TRABAJADOR, SALVO EL CASO DE CONDENA PRIVATIVA DE LA LIBERTAD', 'S.P. DETENCIÓN DEL TRABAJADOR', 'PERFECTA', true),
('04', 'S.P. INHABILITACIÓN ADMINISTRATIVA, JUDICIAL O PENA PRIVATIVA DE LA LIBERTAD EFECTIVA POR DELITO CULPOSO, POR PERIODO NO SUPERIOR A TRES MESES', 'S.P. INHAB. ADMINIST., JUDICIAL O PENA PRIVATIVA', 'PERFECTA', true),
('05', 'S.P. PERMISO, LICENCIA U OTROS MOTIVOS SIN GOCE DE HABER', 'S.P. PERMISO, LICENCIA U OTROS SIN GOCE DE HABER', 'PERFECTA', true),
('06', 'S.P. CASO FORTUITO O FUERZA MAYOR', 'S.P. CASO FORTUITO O FUERZA MAYOR', 'PERFECTA', true),
('07', 'S.P. FALTA NO JUSTIFICADA', 'S.P. FALTA NO JUSTIFICADA', 'PERFECTA', true),
('08', 'S.P. POR TEMPORADA O INTERMITENTE', 'S.P. POR TEMPORADA O INTERMITENTE', 'PERFECTA', true),
('09', 'S.P. MATERNIDAD DURANTE EL DESCANSO PRE Y POST NATAL', 'S.P. MATERNIDAD - PRE Y POST NATAL', 'PERFECTA', true),
('10', 'S.P. SENTENCIA DE PRIMERA INSTANCIA POR DELITOS DE TERRORISMO, NARCOTRÁFICO, CORRUPCIÓN O VIOLACIÓN DE LA LIBERTAD SEXUAL.', 'S.P. SENTENCIA TERR, NARC,CORRUP Y VIOLAC.', 'PERFECTA', true),
('11', 'S.P. IMPOSICIÓN DE MEDIDA CAUTELAR.', 'S.P. IMPOSICIÓN MEDIDA CAUTELAR', 'PERFECTA', true),
('12', 'S.P. ENFERMEDAD GRAVE DEL PADRE, CÓNYUGE, CONVIVIENTE RECONOCIDO JUDICIALMENTE O HIJOS.', 'S.P. ENFERM. PADRE, CÓNYUGE O CONVIVIENTE', 'PERFECTA', true),
('20', 'S.I. ENFERMEDAD O ACCIDENTE (PRIMEROS VEINTE DÍAS)', 'S.I. ENFERM/ACCIDENTE (20 PRIMEROS DÍAS)', 'IMPERFECTA', true),
('21', 'S.I. INCAPACIDAD TEMPORAL (INVALIDEZ, ENFERMEDAD Y ACCIDENTES)', 'S.I. INCAP TEMPORAL (SUBSIDIADO))', 'IMPERFECTA', true),
('22', 'S.I. MATERNIDAD DURANTE EL DESCANSO PRE Y POST NATAL', 'S.I. MATERNIDAD - PRE Y POST NATAL', 'IMPERFECTA', true),
('23', 'S.I. DESCANSO VACACIONAL', 'S.I. DESCANSO VACACIONAL', 'IMPERFECTA', true),
('24', 'S.I. LICENCIA PARA DESEMPEÑAR CARGO CÍVICO Y PARA CUMPLIR CON EL SERVICIO MILITAR OBLIGATORIO', 'S.I. LIC DESEMP CARGO CÍVICO Y PARA SMO', 'IMPERFECTA', true),
('25', 'S.I. PERMISO Y LICENCIA PARA EL DESEMPEÑO DE CARGOS SINDICALES', 'S.I. LIC DESEMPEÑO CARGOS SINDICALES', 'IMPERFECTA', true),
('26', 'S.I. LICENCIA U OTROS MOTIVOS CON GOCE DE HABER', 'S.I. LICENCIA U OTROS MOTIVOS CON GOCE DE HABER', 'IMPERFECTA', true),
('27', 'S.I. DÍAS COMPENSADOS POR HORAS TRABAJADAS EN SOBRETIEMPO', 'S.I. DÍAS COMPENS POR HORAS DE SOBRETIEMPO', 'IMPERFECTA', true),
('28', 'S.I. DÍAS LICENCIA POR PATERNIDAD', 'S.I. DÍAS LICENCIA POR PATERNIDAD', 'IMPERFECTA', true),
('29', 'S.I. DIAS LICENCIA POR ADOPCIÓN', 'S.I. DIAS LICENCIA POR ADOPCIÓN', 'IMPERFECTA', true),
('30', 'S.I. IMPOSICIÓN DE MEDIDA CAUTELAR', 'S.I. IMPOSICIÓN MEDIDA CAUTELAR', 'IMPERFECTA', true),
('31', 'S.I. CITACIÓN EXPRESA JUDICIAL, MILITAR, POLICIAL U OTRAS CITACIONES DERIVADAS DE ACTOS DE ADMINISTRACIÓN INTERNA', 'S.I. CITAC. JUDICIAL, MILITAR, POLICIAL O ADMINIST.', 'IMPERFECTA', true),
('32', 'S.I. FALLECIMIENTO DE PADRES, HERMANOS, CÓNYUGE O HIJOS', 'S.I. FALLECIMIENTO PADRES, HERMANOS, CÓNYUGE O HIJOS', 'IMPERFECTA', true),
('33', 'S.I. ASUMIR REPRESENTACIÓN OFICIAL DEL ESTADO PERUANO EN EVENTOS CIENTÍFICOS, EDUCATIVOS, CULTURALES Y DEPORTIVOS', 'S.I. REPRESENT. DEL ESTADO EN EVENTOS', 'IMPERFECTA', true),
('34', 'S.I. DESC VACACIONAL - LICENCIA ASIST MÉDICA O TERAPIA DE REHABIL DE DEPEND CON DISCAPACIDAD', 'S.I. DESC VACAC LIC POR ASISTE MÉDICA O TERAP REHAB', 'IMPERFECTA', true),
('35', 'S.I. ENFERMEDAD GRAVE O TERMINAL O ACCIDENTE GRAVE DE FAMILIARES DIRECTOS', 'S.I. ENFERM. GRAVE O TERMINAL O ACCIDENTE GRAVE DE FAM DIRECTO', 'IMPERFECTA', true)
ON CONFLICT (codigo) DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS sunat_tipos_suspension;
-- +goose StatementEnd
